name: Lint

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

  validate_hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"
